package me.rerere.workspace

import java.io.File
import java.nio.file.Files

class RootfsPatcher {
    fun patch(
        linuxDir: File,
        options: RootfsPatchOptions = RootfsPatchOptions(),
    ) {
        val etcDir = File(linuxDir, "etc")
        if (etcDir.isDirectory) {
            ensureRootfsDns(etcDir, options.nameservers)
            ensureHosts(etcDir, options.hostname)
            ensureHostname(etcDir, options.hostname)
            ensureLocale(etcDir, options.locale)
            ensureGroupNames(etcDir, options.groupIds.ifEmpty { currentSupplementaryGroupIds() })
        }
        ensureTempDirs(linuxDir)
        ensureMergedUsrLinks(linuxDir)
        ensureShellEntrypoints(linuxDir)
        ensureAptAndDpkgConfigs(linuxDir)
    }

    private fun ensureRootfsDns(
        etcDir: File,
        nameservers: List<String>,
    ) {
        val resolvConf = File(etcDir, "resolv.conf")
        val shouldWrite = when {
            Files.isSymbolicLink(resolvConf.toPath()) -> true
            !resolvConf.exists() -> true
            !resolvConf.isFile -> true
            else -> resolvConf.readText()
                .lineSequence()
                .filter { it.trimStart().startsWith("nameserver ") }
                .none { line ->
                    val server = line.trim().removePrefix("nameserver").trim()
                    server.isNotBlank() && server !in LOCAL_RESOLVERS
                }
        }
        if (!shouldWrite) return

        if (resolvConf.exists() || Files.isSymbolicLink(resolvConf.toPath())) {
            resolvConf.delete()
        }

        val servers = nameservers
            .filter { it.isNotBlank() }
            .distinct()
            .take(MAX_DNS_SERVERS)
            .ifEmpty { DEFAULT_DNS_SERVERS }

        resolvConf.writeText(
            buildString {
                appendLine("# Generated by RikkaHub workspace.")
                servers.forEach { appendLine("nameserver $it") }
                appendLine("options edns0 trust-ad")
            }
        )
    }

    private fun ensureHosts(etcDir: File, hostname: String) {
        val hosts = File(etcDir, "hosts")
        val lines = if (hosts.isFile) hosts.readLines() else emptyList()
        val hasIpv4Localhost = lines.any { line ->
            val normalized = line.substringBefore('#').trim().split(WHITESPACE_REGEX)
            normalized.firstOrNull() == "127.0.0.1" && "localhost" in normalized.drop(1)
        }
        val hasIpv6Localhost = lines.any { line ->
            val normalized = line.substringBefore('#').trim().split(WHITESPACE_REGEX)
            normalized.firstOrNull() == "::1" && "localhost" in normalized.drop(1)
        }
        if (hasIpv4Localhost && hasIpv6Localhost) return

        hosts.parentFile?.mkdirs()
        hosts.appendText(
            buildString {
                if (hosts.exists() && hosts.length() > 0 && !hosts.readText().endsWith('\n')) {
                    appendLine()
                }
                if (!hasIpv4Localhost) {
                    append("127.0.0.1 localhost")
                    if (hostname.isNotBlank() && hostname != "localhost") {
                        append(" ")
                        append(hostname)
                    }
                    appendLine()
                }
                if (!hasIpv6Localhost) {
                    appendLine("::1 localhost ip6-localhost ip6-loopback")
                }
            }
        )
    }

    private fun ensureHostname(etcDir: File, hostname: String) {
        val target = File(etcDir, "hostname")
        if (target.isFile && target.readText().trim().isNotBlank()) return
        target.writeText("${hostname.ifBlank { DEFAULT_HOSTNAME }}\n")
    }

    private fun ensureLocale(etcDir: File, locale: String) {
        val defaultDir = File(etcDir, "default").apply { mkdirs() }
        val target = File(defaultDir, "locale")
        val lines = if (target.isFile) target.readLines().toMutableList() else mutableListOf()
        if (lines.any { it.trim().startsWith("LANG=") }) return
        lines += "LANG=$locale"
        target.writeText(lines.joinToString(separator = "\n", postfix = "\n"))
    }

    private fun ensureGroupNames(etcDir: File, groupIds: List<Long>) {
        val target = File(etcDir, "group")
        if (!target.exists()) {
            target.writeText("root:x:0:\n")
        }
        val lines = target.readLines().toMutableList()
        val existingIds = lines.mapNotNull { line ->
            line.split(':').getOrNull(2)?.toLongOrNull()
        }.toSet()
        val existingNames = lines.mapNotNull { line ->
            line.substringBefore(':').takeIf { it.isNotBlank() }
        }.toSet()
        val additions = groupIds
            .filter { it > 0 && it !in existingIds }
            .distinct()
            .map { id ->
                val baseName = "android_gid_$id"
                val name = if (baseName in existingNames) "${baseName}_workspace" else baseName
                "$name:x:$id:"
            }
        if (additions.isEmpty()) return

        target.appendText(
            buildString {
                if (target.length() > 0 && !target.readText().endsWith('\n')) {
                    appendLine()
                }
                additions.forEach { appendLine(it) }
            }
        )
    }

    private fun ensureTempDirs(linuxDir: File) {
        listOf("tmp", "var/tmp", "root").forEach { path ->
            File(linuxDir, path).mkdirs()
        }
        listOf(File(linuxDir, "tmp"), File(linuxDir, "var/tmp")).forEach { dir ->
            dir.setReadable(true, false)
            dir.setWritable(true, false)
            dir.setExecutable(true, false)
        }
        File(linuxDir, "root").apply {
            setReadable(true, true)
            setWritable(true, true)
            setExecutable(true, true)
        }
    }

    private fun ensureShellEntrypoints(linuxDir: File) {
        val usrBinDir = File(linuxDir, "usr/bin")
        val binDir = File(linuxDir, "bin")
        val sh = File(binDir, "sh")
        if (sh.exists()) return

        val source = listOf(
            File(usrBinDir, "sh"),
            File(usrBinDir, "bash"),
            File(binDir, "bash"),
        ).firstOrNull { it.isFile } ?: return
        if (runCatching { sh.canonicalFile == source.canonicalFile }.getOrDefault(false)) return

        sh.parentFile?.mkdirs()
        runCatching {
            val parent = sh.parentFile ?: return@runCatching
            val relativeTarget = if (Files.isSymbolicLink(parent.toPath())) {
                // If bin is a symlink to usr/bin, resolve the target relative to the canonical path
                parent.canonicalFile.toPath().relativize(source.toPath())
            } else {
                parent.toPath().relativize(source.toPath())
            }
            Files.createSymbolicLink(sh.toPath(), relativeTarget)
        }.recoverCatching {
            source.copyTo(sh, overwrite = true)
            sh.setReadable(source.canRead(), false)
            sh.setWritable(source.canWrite(), true)
            sh.setExecutable(source.canExecute(), false)
        }.getOrNull()
    }

    private fun ensureAptAndDpkgConfigs(linuxDir: File) {
        val etcDir = File(linuxDir, "etc")
        
        // Prevent dpkg from calling sync() which can be extremely slow or fail in proot on Android
        val dpkgCfgDir = File(etcDir, "dpkg/dpkg.cfg.d")
        dpkgCfgDir.mkdirs()
        File(dpkgCfgDir, "force-unsafe-io").writeText("force-unsafe-io\n")

        // Prevent services from starting during package installation
        val policy = File(linuxDir, "usr/sbin/policy-rc.d")
        policy.parentFile?.mkdirs()
        if (!policy.exists()) {
            policy.writeText("#!/bin/sh\nexit 101\n")
            policy.setExecutable(true, false)
        }

        // Disable apt-get sandboxing to avoid _apt user permission issues in proot
        val aptConfDir = File(etcDir, "apt/apt.conf.d")
        aptConfDir.mkdirs()
        File(aptConfDir, "99proot-sandbox").writeText("APT::Sandbox::User \"root\";\n")
    }

    private fun ensureMergedUsrLinks(linuxDir: File) {
        ensureMergedUsrLink(linuxDir, "bin", "usr/bin")
        ensureMergedUsrLink(linuxDir, "sbin", "usr/sbin")
        ensureMergedUsrLink(linuxDir, "lib", "usr/lib")
        ensureMergedUsrLink(linuxDir, "lib64", "usr/lib64")
    }

    private fun ensureMergedUsrLink(
        linuxDir: File,
        linkPath: String,
        targetPath: String,
    ) {
        val link = File(linuxDir, linkPath)
        val target = File(linuxDir, targetPath)
        if (!target.exists()) return
        if (Files.isSymbolicLink(link.toPath())) return

        if (!link.exists()) {
            link.parentFile?.mkdirs()
            runCatching {
                Files.createSymbolicLink(link.toPath(), File(targetPath).toPath())
            }.recoverCatching {
                if (target.isDirectory) {
                    target.copyRecursively(link, overwrite = true)
                } else {
                    target.copyTo(link, overwrite = true)
                    link.setReadable(target.canRead(), false)
                    link.setWritable(target.canWrite(), true)
                    link.setExecutable(target.canExecute(), false)
                }
            }.getOrNull()
            return
        }

        if (link.isDirectory && target.isDirectory) {
            val tempLink = File(link.parentFile, "${link.name}.rikkahub-tmp")
            runCatching {
                Files.createSymbolicLink(tempLink.toPath(), File(targetPath).toPath())
            }.onSuccess {
                link.listFiles()?.forEach { child ->
                    val dest = File(target, child.name)
                    if (!dest.exists()) {
                        child.renameTo(dest)
                    }
                }
                link.deleteRecursively()
                tempLink.renameTo(link)
            }.onFailure {
                tempLink.delete()
            }
        }
    }

    private fun currentSupplementaryGroupIds(): List<Long> {
        val status = File("/proc/self/status")
        if (!status.isFile) return emptyList()
        val groups = status.readLines().firstOrNull { it.startsWith("Groups:") } ?: return emptyList()
        return groups
            .removePrefix("Groups:")
            .trim()
            .split(WHITESPACE_REGEX)
            .mapNotNull { it.toLongOrNull() }
    }

    private companion object {
        private const val MAX_DNS_SERVERS = 3
        private const val DEFAULT_HOSTNAME = "localhost"
        private val WHITESPACE_REGEX = Regex("\\s+")
        private val LOCAL_RESOLVERS = setOf(
            "127.0.0.1",
            "127.0.0.53",
            "::1",
        )
        private val DEFAULT_DNS_SERVERS = listOf(
            "1.1.1.1",
            "8.8.8.8",
            "223.5.5.5",
        )
    }
}

data class RootfsPatchOptions(
    val nameservers: List<String> = emptyList(),
    val hostname: String = "localhost",
    val locale: String = "C.UTF-8",
    val groupIds: List<Long> = emptyList(),
)
