package me.rerere.rikkahub.ui.components.ui.icons

import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.rounded.*
import androidx.compose.ui.graphics.vector.ImageVector

object ModeIcons {
    // A map of icon name to ImageVector
    // Add more icons as needed
    val AllIcons = mapOf(
        "auto_fix_high" to Icons.Rounded.AutoFixHigh,
        "person" to Icons.Rounded.Person,
        "code" to Icons.Rounded.Code,
        "edit" to Icons.Rounded.Edit,
        "brush" to Icons.Rounded.Brush,
        "chat" to Icons.Rounded.Chat,
        "school" to Icons.Rounded.School,
        "work" to Icons.Rounded.Work,
        "science" to Icons.Rounded.Science,
        "translate" to Icons.Rounded.Translate,
        "security" to Icons.Rounded.Security,
        "games" to Icons.Rounded.Games,
        "movie" to Icons.Rounded.Movie,
        "music_note" to Icons.Rounded.MusicNote,
        "image" to Icons.Rounded.Image,
        "book" to Icons.Rounded.Book,
        "build" to Icons.Rounded.Build,
        "settings" to Icons.Rounded.Settings,
        "star" to Icons.Rounded.Star,
        "favorite" to Icons.Rounded.Favorite,
        "search" to Icons.Rounded.Search,
        "home" to Icons.Rounded.Home,
        "menu" to Icons.Rounded.Menu,
        "close" to Icons.Rounded.Close,
        "add" to Icons.Rounded.Add,
        "delete" to Icons.Rounded.Delete,
        "account_circle" to Icons.Rounded.AccountCircle,
        "info" to Icons.Rounded.Info,
        "warning" to Icons.Rounded.Warning,
        "error" to Icons.Rounded.Error,
        "check" to Icons.Rounded.Check,
        "play_arrow" to Icons.Rounded.PlayArrow,
        "pause" to Icons.Rounded.Pause,
        "stop" to Icons.Rounded.Stop,
        "refresh" to Icons.Rounded.Refresh,
        "lock" to Icons.Rounded.Lock,
        "unlock" to Icons.Rounded.LockOpen,
        "visibility" to Icons.Rounded.Visibility,
        "visibility_off" to Icons.Rounded.VisibilityOff,
        "email" to Icons.Rounded.Email,
        "phone" to Icons.Rounded.Phone,
        "camera_alt" to Icons.Rounded.CameraAlt,
        "mic" to Icons.Rounded.Mic,
        "videocam" to Icons.Rounded.Videocam,
        "location_on" to Icons.Rounded.LocationOn,
        "map" to Icons.Rounded.Map,
        "shopping_cart" to Icons.Rounded.ShoppingCart,
        "attach_file" to Icons.Rounded.AttachFile,
        "cloud" to Icons.Rounded.Cloud,
        "folder" to Icons.Rounded.Folder,
        "insert_drive_file" to Icons.Rounded.InsertDriveFile,
        "assignment" to Icons.Rounded.Assignment,
        "description" to Icons.Rounded.Description,
        "note" to Icons.Rounded.Note,
        "event" to Icons.Rounded.Event,
        "schedule" to Icons.Rounded.Schedule,
        "alarm" to Icons.Rounded.Alarm,
        "timer" to Icons.Rounded.Timer,
        "lightbulb" to Icons.Rounded.Lightbulb,
        "emoji_objects" to Icons.Rounded.EmojiObjects,
        "psychology" to Icons.Rounded.Psychology,
        "calculate" to Icons.Rounded.Calculate,
        "engineering" to Icons.Rounded.Engineering,
        "history_edu" to Icons.Rounded.HistoryEdu,
        "sports_esports" to Icons.Rounded.SportsEsports,
        "restaurant" to Icons.Rounded.Restaurant,
        "local_cafe" to Icons.Rounded.LocalCafe,
        "flight" to Icons.Rounded.Flight,
        "directions_car" to Icons.Rounded.DirectionsCar,
        "train" to Icons.Rounded.Train,
        "palette" to Icons.Rounded.Palette,
        "theater_comedy" to Icons.Rounded.TheaterComedy,
        "bug_report" to Icons.Rounded.BugReport,
        "android" to Icons.Rounded.Android,
        "computer" to Icons.Rounded.Computer,
        "smartphone" to Icons.Rounded.Smartphone,
        "terminal" to Icons.Rounded.Terminal,
        "javascript" to Icons.Rounded.Javascript,
        "html" to Icons.Rounded.Html,
        "css" to Icons.Rounded.Css,
        "php" to Icons.Rounded.Php,
        "data_object" to Icons.Rounded.DataObject,
        "rocket_launch" to Icons.Rounded.RocketLaunch,
        "bolt" to Icons.Rounded.Bolt,
        "flash_on" to Icons.Rounded.FlashOn,
        "category" to Icons.Rounded.Category
    )

    fun getIcon(name: String?): ImageVector {
        return AllIcons[name] ?: Icons.Rounded.Category
    }
}
